version: "3.8"
services:
  nacos:
    image: nacos/nacos-server
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
    ports:
      - "8848:8848"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: default
    ports:
      - "3306:3306"
  postgres:
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:alpine
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"