version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    